Repository likecoin/likecoin-app, pull requests merged in 2020-02, with the labels that each got.

#120 Handle non-LikeCoin-button-integrated contents
  app/components/content-list-item/content-list-item.tsx
  app/models/content/content.ts
Labels: feature

#122 📄 Add open source license link in settings screen
  app/i18n/en.json
  app/i18n/zh-Hant-HK.json
  app/screens/settings-screen/settings-screen.tsx
Labels: enhancement

#123 🐛 Fix fetching content details without liker ID
  app/models/content/content.ts
Labels: bug

#124 ✨ Improve scrolling experience on iOS
  app/screens/content-view-screen/content-view-screen.tsx
Labels: enhancement
