Repository likecoin/likecoin-app, pull requests merged in 2020-01, with the labels that each got.

#76 Reader bugfixes & show display name of content creator
  app/components/content-list-item/content-list-item.tsx
  app/components/content-list/content-list.props.ts
  app/components/loading-likecoin/index.ts
  app/components/loading-likecoin/loading-likecoin.tsx
  app/models/authcore-store/authcore-store.ts
  app/models/content/content.ts
  app/models/creator/creator.test.ts
  app/models/creator/creator.ts
  app/models/creator/index.ts
  app/models/reader-store/reader-store.ts
  app/models/root-store/setup-root-store.ts
  app/navigation/reader-navigator.tsx
  app/screens/likerland-oauth-screen/likerland-oauth-screen.style.ts
  app/screens/likerland-oauth-screen/likerland-oauth-screen.tsx
  app/screens/reader-screen/reader-screen.tsx
  app/services/api/likerland-api.ts
Labels: bug, feature

#83 🐛 Resolve balance out-sync after undelegating
  app/screens/staking-unbonding-delegation-signing-screen/staking-unbonding-delegation-signing-screen.tsx
Labels: bug

#84 📈 Add events log
  .env
  app/models/user-store/user-store.ts
  app/navigation/navigation-store.ts
  app/screens/content-view-screen/content-view-screen.tsx
  app/screens/reader-screen/reader-screen.tsx
  app/screens/receive-screen/receive-screen.tsx
  app/screens/registration-screen/registration-screen.tsx
  app/screens/settings-screen/settings-screen.tsx
  app/screens/sign-in-screen/sign-in-screen.tsx
  app/screens/staking-delegation-amount-input-screen/staking-delegation-amount-input-screen.tsx
  app/screens/staking-delegation-signing-screen/staking-delegation-signing-screen.tsx
  app/screens/staking-rewards-withdraw-screen/staking-rewards-withdraw-screen.tsx
  app/screens/staking-unbonding-delegation-amount-input-screen/staking-unbonding-delegation-amount-input-screen.tsx
  app/screens/staking-unbonding-delegation-signing-screen/staking-unbonding-delegation-signing-screen.tsx
  app/screens/subscription-screen/subscription-screen.tsx
  app/screens/transfer-amount-input-screen/transfer-amount-input-screen.tsx
  app/screens/transfer-signing-screen/transfer-signing-screen.tsx
  app/screens/transfer-target-input-screen/transfer-target-input-screen.tsx
  app/screens/validator-screen/validator-screen.tsx
  app/screens/wallet-dashboard-screen/wallet-dashboard-screen.tsx
  app/services/app-config/app-config.ts
  app/utils/analytics.ts
  app/utils/error.ts
  app/utils/firebase.ts
  app/utils/sentry.ts
  test/mock-firebase.ts
Labels: enhancement

#89 🐛 Fix non-string type analytics value crash analytics
  app/utils/analytics.ts
Labels: bug

#88 🐛 Fix logout crash
  app/utils/firebase.ts
Labels: bug

#87 Improve TxStoreModel & its dependants references
  app/models/staking-delegation-store/staking-delegation-store.ts
  app/models/staking-rewards-withdraw-store/staking-rewards-withdraw-store.ts
  app/models/staking-unbonding-delegation-store/staking-unbonding-delegation-store.ts
  app/models/transfer-store/transfer-store.ts
  app/models/tx-store/tx-store.ts
Labels: enhancement

#90 ✨ Add Civic Liker halo to avatar
  app/components/avatar/avatar.props.ts
  app/components/avatar/avatar.style.ts
  app/components/avatar/avatar.tsx
  app/components/avatar/civic-liker-halo.svg
  app/components/avatar/index.ts
  app/models/user-store/user-store.ts
  app/models/user/user.ts
  app/screens/settings-screen/settings-screen.tsx
  app/screens/wallet-dashboard-screen/wallet-dashboard-screen.tsx
  app/services/api/api.types.ts
Labels: feature

#92 ⚡️ Upgrade react-native-webview@8 to detect history nav change
  app/screens/likerland-oauth-screen/likerland-oauth-screen.tsx
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: enhancement

#94 🎨 Append user agent of device instead of override
  app/screens/content-view-screen/content-view-screen.tsx
  app/screens/likerland-oauth-screen/likerland-oauth-screen.tsx
  app/services/api/api-config.ts
Labels: enhancement

#93 Better handle auth flow
  app/app.tsx
  app/components/loading-likecoin/loading-likecoin.tsx
  app/components/loading-screen/index.ts
  app/components/loading-screen/loading-screen.tsx
  app/i18n/en.json
  app/i18n/zh-Hant-HK.json
  app/models/root-store/root-store.ts
  app/models/root-store/setup-root-store.ts
  app/models/user-store/user-store.ts
  app/screens/auth-loading-screen/auth-loading-screen.tsx
  app/screens/settings-screen/settings-screen.tsx
  app/screens/sign-in-screen/sign-in-screen.tsx
  app/services/api/api-config.ts
  app/services/api/likeco-api.ts
  app/services/api/likerland-api.ts
Labels: bug, enhancement

#97 🐛 Fix validator payload in analytics
  app/screens/wallet-dashboard-screen/wallet-dashboard-screen.tsx
Labels: bug

#96 Fix unauthenticated alerts
  app/models/root-store/root-store.ts
Labels: bug

#100 Mitigate cookies issue
  app/i18n/en.json
  app/i18n/zh-Hant-HK.json
  app/models/reader-store/reader-store.ts
  app/models/user-store/user-store.ts
  app/screens/auth-loading-screen/auth-loading-screen.tsx
  app/screens/likerland-oauth-screen/likerland-oauth-screen.tsx
  app/screens/registration-screen/registration-screen.tsx
  app/screens/sign-in-screen/sign-in-screen.tsx
  app/services/api/likerland-api.ts
  ios/LikeCoinApp/LKCWebView.m
  ios/LikeCoinApp/RNCWebView+LikeCoin.h
Labels: bug, enhancement

#101 Updates for reader
  app/components/content-list-item/content-list-item.tsx
  app/models/content/content.ts
  app/models/root-store/setup-root-store.ts
  app/screens/bookmark-screen/bookmark-screen.tsx
Labels: enhancement

#103 Hotfix on Android sign in
  .env
  android/app/build.gradle
  app/screens/likerland-oauth-screen/likerland-oauth-screen.tsx
  ios/LikeCoinApp.xcodeproj/project.pbxproj
  package.json
Labels: bug

#106 Hotfix on undelegation
  .env
  android/app/build.gradle
  app/screens/likerland-oauth-screen/likerland-oauth-screen.tsx
  app/screens/staking-unbonding-delegation-amount-input-screen/staking-unbonding-delegation-amount-input-screen.tsx
  ios/LikeCoinApp.xcodeproj/project.pbxproj
  package.json
Labels: bug

#105 Add pull to refresh in validator screen
  app/i18n/en.json
  app/i18n/zh-Hant-HK.json
  app/models/chain-store/chain-store.ts
  app/models/validator/validator.ts
  app/screens/validator-screen/validator-screen.tsx
  app/services/cosmos/cosmos.ts
  app/services/cosmos/cosmos.utils.ts
Labels: feature

#109 Hotfix on ContentListItem
  .env
  android/app/build.gradle
  app/components/content-list-item/content-list-item.tsx
  app/models/content/content.ts
  ios/LikeCoinApp.xcodeproj/project.pbxproj
  package.json
Labels: bug

#111 Add redelegation lock
  app/components/button-group/button-group.tsx
  app/components/button/button.presets.ts
  app/components/icon/icons/index.ts
  app/components/icon/icons/lock.svg
  app/components/text/text.props.ts
  app/components/text/text.tsx
  app/i18n/en.json
  app/i18n/zh-Hant-HK.json
  app/models/chain-store/chain-store.ts
  app/models/wallet/wallet.ts
  app/screens/staking-redelegation-signing-screen/staking-redelegation-signing-screen.tsx
  app/screens/validator-screen/validator-screen.tsx
  app/screens/wallet-dashboard-screen/wallet-dashboard-screen.tsx
  app/services/cosmos/cosmos.ts
  app/services/cosmos/cosmos.types.ts
Labels: feature

#112 Fix delegation & update status badge
  README.md
  app/screens/staking-delegation-signing-screen/staking-delegation-signing-screen.tsx
Labels: bug, documentation
